name: 'Format, Build, Lint, and Test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Hello
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          module: github.com/shykes/daggerverse/hello
          args: node --loader ts-node/esm ./cicd.mts

